version: '3.8'

services:
  api:
    build: ./api
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/api/client.json
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GPT_API_KEY=${GPT_API_KEY}
      - OPENAI_API_KEY=${GPT_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # プロジェクトルート全体をマウント
      - ./data:/app/data # これは重複するが、明示的に残しても良い
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  app:
    build: ./app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    command: streamlit run app/main.py --server.port 8501 --server.address 0.0.0.0
